In [3]:
from sklearn import model_selection, datasets
import numpy as np

In [4]:
iris = datasets.load_iris()

In [6]:
train_data, test_data, train_labels, test_labels = model_selection.train_test_split(iris.data, iris.target, test_size = 0.3)

In [7]:
len(test_labels)/len(iris.data)

0.3

In [10]:
print('Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data)))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [8]:
print('Обучающая выборка:\n', train_data[:5])
print('\n')
print('Тестовая выборка:\n', test_data[:5])

Обучающая выборка:
 [[4.4 3.  1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [5.8 2.6 4.  1.2]
 [5.2 3.4 1.4 0.2]
 [4.8 3.  1.4 0.3]]


Тестовая выборка:
 [[6.3 2.5 4.9 1.5]
 [5.4 3.  4.5 1.5]
 [5.9 3.2 4.8 1.8]
 [4.9 2.4 3.3 1. ]
 [5.5 3.5 1.3 0.2]]


In [9]:
print('Метки классов на обучающей выборке:\n', train_labels)
print('\n')
print('Метки классов на тестовой выборке:\n', test_labels)

Метки классов на обучающей выборке:
 [0 0 1 0 0 0 2 2 2 1 1 0 2 1 2 1 1 0 1 2 0 2 0 1 0 1 2 0 2 0 1 0 1 1 2 0 2
 0 0 0 0 2 1 2 2 1 0 2 2 1 2 1 0 0 1 0 1 0 0 0 1 2 0 2 0 2 0 2 0 1 2 1 2 1
 1 0 2 1 2 0 1 1 1 0 1 1 2 0 2 0 1 2 1 0 1 2 0 2 1 2 2 0 0 1 2]


Метки классов на тестовой выборке:
 [1 1 1 1 0 2 2 1 2 1 2 1 1 2 0 2 1 0 2 0 1 1 1 1 0 1 2 0 2 0 2 0 0 2 0 2 1
 2 0 1 2 0 2 2 2]


# Стратегии кросс-валидации
### KFold
**shuffle** - перемешать когда датасет отсортирован <br>
**random_state** - указываем чтобы всегда одинакого перемешивалось и был воспроизводимый результат

In [14]:
X = range(0,10)
X

range(0, 10)

In [15]:
kf = model_selection.KFold(n_splits = 5)
for train_indices, test_indices in kf.split(test_data):
    print(train_indices, test_indices)

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44] [0 1 2 3 4 5 6 7 8]
[ 0  1  2  3  4  5  6  7  8 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44] [ 9 10 11 12 13 14 15 16 17]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44] [18 19 20 21 22 23 24 25 26]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 36 37 38 39 40 41 42 43 44] [27 28 29 30 31 32 33 34 35]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35] [36 37 38 39 40 41 42 43 44]


In [16]:
kf = model_selection.KFold(n_splits = 5, shuffle = True)
for train_indices, test_indices in kf.split(test_data):
    print(train_indices, test_indices)

[ 0  1  2  3  4  5  6  7  8  9 10 14 15 16 17 18 19 20 22 24 27 28 30 31
 32 33 35 36 37 38 39 40 41 42 43 44] [11 12 13 21 23 25 26 29 34]
[ 0  1  2  3  4  5  7  9 10 11 12 13 14 15 16 17 18 19 21 23 25 26 27 29
 30 31 32 34 35 37 38 39 41 42 43 44] [ 6  8 20 22 24 28 33 36 40]
[ 1  2  3  6  7  8 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 31 32 33 34 35 36 37 39 40 43] [ 0  4  5  9 30 38 41 42 44]
[ 0  1  2  3  4  5  6  8  9 11 12 13 14 18 19 20 21 22 23 24 25 26 28 29
 30 32 33 34 35 36 38 40 41 42 43 44] [ 7 10 15 16 17 27 31 37 39]
[ 0  4  5  6  7  8  9 10 11 12 13 15 16 17 20 21 22 23 24 25 26 27 28 29
 30 31 33 34 36 37 38 39 40 41 42 44] [ 1  2  3 14 18 19 32 35 43]


In [24]:
kf = model_selection.KFold(n_splits = 5, shuffle=True, random_state=0)
for train_indices, test_indices in kf.split(X):
    print(train_indices, test_indices)

[0 1 3 4 5 6 7 9] [2 8]
[0 1 2 3 5 6 7 8] [4 9]
[0 2 3 4 5 7 8 9] [1 6]
[0 1 2 4 5 6 8 9] [3 7]
[1 2 3 4 6 7 8 9] [0 5]


### Stratified fold

сохроняет сооношение классов в подвыборках!) очень удобно

In [23]:
y = np.array([0] * 5 + [1] *5)
print(y)
skf = model_selection.StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
for train_indices, test_indices in skf.split(X, y):
    print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[0 2 3 4 6 7 8 9] [1 5]
[0 1 3 4 5 6 8 9] [2 7]
[1 2 3 4 5 7 8 9] [0 6]
[0 1 2 4 5 6 7 8] [3 9]
[0 1 2 3 5 6 7 9] [4 8]


### shuffle split

следующее разбиение не зависи от предыдущей. можно много сетов получить сразу

In [26]:
ss = model_selection.ShuffleSplit(n_splits = 10, test_size = 0.2)

for train_indices, test_indices in ss.split(X):
    print(train_indices, test_indices)

[4 5 2 1 9 7 6 8] [3 0]
[0 8 5 3 1 4 7 9] [2 6]
[2 5 3 7 1 9 8 0] [6 4]
[6 5 2 3 1 9 4 0] [7 8]
[7 8 9 1 4 6 3 2] [0 5]
[2 4 1 9 8 3 0 5] [6 7]
[7 1 0 9 8 5 3 6] [2 4]
[9 6 1 2 7 3 5 0] [8 4]
[1 7 9 3 0 2 4 8] [5 6]
[0 4 1 2 8 3 6 7] [5 9]


### Stratified shuffle split

так же не зависит от предыдущей но делает сбалансированую выборку по классам


In [ ]:
target = np.array([0] * 5 + [1] * 5)
print(target)

sss = model_selection.StratifiedShuffleSplit(n_splits = 4, test_size = 0.2)
for train_indices, test_indices in sss.split(X, target):
    print(train_indices, test_indices)

### Leave one out
каждый обьект 1 раз оставояем в тесте - в тесте 1 обьект только.
удобно когда выборка не большая

In [27]:
loo = model_selection.LeaveOneOut()

for train_indices, test_index in loo.split(X):
    print(train_indices, test_index)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]
